name: Page Build
on:
  page_build

jobs:
  pagebuild:
    runs-on: ubuntu-latest
    steps:    
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: firebolt-db/firebolt-doc-to-guru
          event-type: prod_build
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
