name: GitHub to Guru
on:
  push:
    branches:
      - gh-pages
      
      
jobs:
  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up requirements
        run: |
          pip3 install -r "scripts/requirements.txt"; 
      - name: Run scripts
        run: rm "./guru/cards.yaml"; rm "./guru/collection.yaml"; rm "./guru/boards.yaml"; rm "./guru/boardgroups.yaml"; python3 scripts/create_card_yaml.py "./docs" "./guru/cards.yaml"  "./guru/collection.yaml"; python3 scripts/create_board_yaml.py "./docs" "./guru/boards.yaml" "./guru/boardgroups.yaml";
        shell: sh
      - name: Push new yaml files 
        run: git add guru/.; git commit -m"auto update yaml"; git fetch origin gh-pages; git push origin HEAD:gh-pages;
  guru:
    runs-on: ubuntu-latest
    needs: yaml
    steps:
    - uses: actions/checkout@v1
    - uses: peckjon/github-to-guru@master
      env:
        GURU_USER_EMAIL:  '${{ secrets.GURU_USER_EMAIL }}'
        GURU_USER_TOKEN:  '${{ secrets.GURU_USER_TOKEN }}'
        GURU_COLLECTION_ID: 'd345adef-5855-4bff-94b2-ed4cd0d568af'
        GURU_CARD_FOOTER: 'To edit this card, visit https://github.com/${{ github.repository }}/tree/gh-pages/__CARDPATH__'
        GURU_COLLECTION_YAML: 'guru/collection.yaml'
        GURU_CARD_YAML: 'guru/cards.yaml'
        GURU_BOARD_YAML: 'guru/boards.yaml'
        GURU_BOARDGROUP_YAML: 'guru/boardgroups.yaml'
